CREATE DATABASE sistemas_pagos;
USE sistemas_pagos;

CREATE TABLE PAGO (
    ID_PAGO INT NOT NULL AUTO_INCREMENT,
    RUT BIGINT NOT NULL,
    DV VARCHAR(1) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    DIRECCION VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONO BIGINT,
    CIUDAD VARCHAR(35) NOT NULL,
    CODIGO_POSTAL VARCHAR(50) NOT NULL,
    PAIS VARCHAR(25) NOT NULL,
    REGION VARCHAR(25) NOT NULL,
    COMUNA VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID_PAGO)
);