spring.application.name=pagos

# 1. URL con la ruta exacta de tu escritorio
spring.datasource.url=jdbc:oracle:thin:@uvhbz4aynzie2s9y_high?TNS_ADMIN=C:/Users/va-alumno/Desktop/Wallet_UVHBZ4AYNZIE2S9Y

# 2. Credenciales
spring.datasource.username=ADMIN
spring.datasource.password=DuocFullstack200

# 3. Driver y Dialecto
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# 4. Validación de tabla existente
spring.jpa.hibernate.ddl-auto=validate